spring:
  application:
    name: cloud-server
  datasource:
    url: jdbc:mysql://60.204.237.239:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: mysqlTest@1234


server:
  port: 9999

logging:
  level:
    org.springframework.security: debug

jwt:
  secret: 5OfGky1sHcWT5EMZYGkGkHfIWq1hTFr5uBWuMiJQyww=  # 256-bit Base64
  expiration: 3600000  # 1小时