spring:
  application:
    name: system-server
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: 60.204.237.239:8848
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
        namespace: 063701af-ad31-403f-bb51-934ddc05118b
      config:
        server-addr: 60.204.237.239:8848
        username: ${NACOS_USERNAME}
        password: ${NACOS_PASSWORD}
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: 063701af-ad31-403f-bb51-934ddc05118b

  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml # 加载本地配置
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml # 加载nacos配置 下面的优先级高

server:
  port: 9091

logging:
  file:
    path: ./logs


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml   # Mapper XML 路径
  type-aliases-package: org.xy.cloud.**.domain # 实体类包路径
  global-config:
    db-config:
      id-type: auto     # 主键策略：auto、input、assign_id等
      logic-delete-value: 1    # 逻辑删除值
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 日志实现，开发调试用
  # 其他配置，如分页插件等可以加在这里
